### ISSUE TITLE
As a researcher, I want to receive an access code so that I may create an admin account.

### ISSUE THREAD

**Issue by agretta** [agretta/sleep-as-a-symptom#2]
Scenario: The researcher successfully adds another researcher to the admin list.
Given: Another researcher has added the new researcher’s email to the admin list;
When: The other researcher successfully adds the email to the admin list;
Then: an email should be sent to this email containing an access code for use in signing in.

Scenario: The researcher successfully adds another researcher to the admin list, but the researcher deletes or does not receive the email.
Given: Another researcher has added the new researcher’s email to the admin list, and this user wants to create an admin account;
When: The new researcher does not have the email containing the access code, so they click a request access code button;
Then: an email should be sent to this email containing an access code for use in signing in if they are on the admin list.

**Comment by Sc0urg3r** [comment]
Feature implemented in other tasks
