### ISSUE TITLE
As a user I want to create an account so that I can use the app.

### ISSUE THREAD

**Issue by agretta** [agretta/sleep-as-a-symptom#26]
- [x] Email box
- [x] Password/confirm password box
- [ ] researcher code input box
- [ ]  register and cancel buttons
- [ ] link to login
- [ ] password security
- [ ] email validity
* Note that this list is not necessarily exhaustive of the user story and is just my guess

**Comment by graham-ely** [comment]
@Sc0urg3r Can we add a confirmation that a user has been created (or maybe just advance straight to dashboard)? Right now I'm not getting any visual confirmation that the account is created until I hit sign up again and get a email in use error
